blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/bowlingball3525/Meccha-Chameleon-Peterhack/discussions
    about: Please ask questions and start discussions here
